workflows:
  android-app:
    name: Build Android APK
    max_build_duration: 60
    environment:
      android: true
      java: 17
    scripts:
      - name: Build APK
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
